### ISSUE TITLE
bug: After executing nanocl install --docker-host unix:///var/run/docker.sock, nanocld fails to start.

### ISSUE THREAD

**Issue by NicholasLiuWei** [nxthat/nanocl#1034]
![image](https://github.com/user-attachments/assets/a271a0df-38c9-422f-b568-5917b06b5b7d)

docker logs -f 80ce61a3ed89

![image](https://github.com/user-attachments/assets/fd2d7efd-1bd8-4815-85c4-35820eebdf4e)

how does the request postgresql://root:root@store.nanocl.internal:26258/defaultdb connect to CockroachDB? CockroachDB exposes only port 26257

**Comment by 0xle0ne** [comment]
Hey thanks for the report, the ports listed in `docker ps` command are the port that are set using the EXPOSE keywork from the cockroachdb Dockerfile as described there: https://docs.docker.com/reference/dockerfile/#expose

The port 26258 is set from the installation template there:
https://github.com/next-hat/nanocl/blob/nightly/installer.yml#L34

The communication is enabled only internally, meaning that it go through the docker network.

If you use the default unix path for the docker socket witch is `unix:///var/run/docker.sock`
You can avoid using the options `--docker-host`

Can you try to uninstall and install again using:

```sh
nanocl uninstall
sudo rm -rf /var/lib/nanocl
nanocl install
```

**Comment by 0xle0ne** [comment]
Also could you link your docker version using the `docker version` command

**Comment by NicholasLiuWei** [comment]
Thank you for your prompt response! I really appreciate your help.
use nanocl ninstall and install again,nanocld still cannot be started and the same error is reported。
![image](https://github.com/user-attachments/assets/b643bccc-d9d2-4dca-94cf-686870a5f902)

**Comment by 0xle0ne** [comment]
That's really unexpected, we have e2e tests for that, can you inspect the docker network "system" and show me the output please?

**Comment by NicholasLiuWei** [comment]
[
    {
        "Name": "system",
        "Id": "baa8a728c6795c4d9f6364c91fecd60f8013e7378f15257b7662dce8e1535300",
        "Created": "2024-08-20T15:51:47.375060469+08:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "Gateway": "172.18.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "bfcf236154b3f4836cde2dc5e427c1eca427e87fc0b971e32dd2da69d423a2e6": {
                "Name": "nstore.system.c",
                "EndpointID": "d63d50dac91d79e14ed3e4b06227f6f96b10f1646bc7f6d94c458038dd076ff2",
                "MacAddress": "02:42:ac:12:00:02",
                "IPv4Address": "172.18.0.2/16",
                "IPv6Address": ""
            },
            "e23f1fcbf9a46eccf9036e5a297cbe1af500ee87f776796b1aa8332f919af8b7": {
                "Name": "nmetrics.system.c",
                "EndpointID": "6ad9afc7582113731078934e9d5c3ae378bb9620d1aeb0cfc8c706f0f6ec6920",
                "MacAddress": "02:42:ac:12:00:03",
                "IPv4Address": "172.18.0.3/16",
                "IPv6Address": ""
            },
            "e5198700d4353dd8045104a2b9b16136d467ffc25cf897f5c51d5da7bab23f14": {
                "Name": "ncdns.system.c",
                "EndpointID": "13c5297b027fd2e75f74d5496a4b2bb44f0b4f8adb63bef1a4ad577a66ce7694",
                "MacAddress": "02:42:ac:12:00:05",
                "IPv4Address": "172.18.0.5/16",
                "IPv6Address": ""
            },
            "f78fb027ffb8aefc26548a7ba1b432aa30b984f4e94f1d9eb1e1d30251eb3f17": {
                "Name": "ncproxy.system.c",
                "EndpointID": "e1f7b974c43df866c8890c4a998547d6f096d1b461ad19103790706696633508",
                "MacAddress": "02:42:ac:12:00:04",
                "IPv4Address": "172.18.0.4/16",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.bridge.name": "nanocl.system"
        },
        "Labels": {}
    }
]

**Comment by NicholasLiuWei** [comment]
[system-network.json](https://github.com/user-attachments/files/16688970/system-network.json)

Can  use "nstore.system.c" instead of "store.nanocl.internal" ?

**Comment by NicholasLiuWei** [comment]
Thank you very much for your patience. I upgraded Docker to version 26.0.0, which resolved the issue.

**Comment by 0xle0ne** [comment]
My pleasure, I'm glad you found a way to fix it, let me know if you need more help!
