### ISSUE TITLE
Feature: Create a type `VirtualMachine` for a State File

### ISSUE THREAD

**Issue by 0xle0ne** [nxthat/nanocl#197]
**Is your feature request related to a problem? Please describe.**
Like for cargoes we should be able to create set a virtual machine from a **state file**

**Describe the solution you'd like**
Create a new `VirtualMachineState` model with a new type and accept it inside our **state service** to `create`, `patch` and `delete` them. The model should be added inside `crates/nanocl_stubs/src/state.rs` the function to `create`, `patch` and `delete` a virtual machine already exists inside `bin/nanocld/src/utils/vm.rs`

**Comment by ver-nyan** [comment]
If anyone hasn't started on this, I can take a stab at it. :3

**Comment by 0xle0ne** [comment]
I asked @cszach if he started something i wait for his return, because it's quite similar to this one https://github.com/nxthat/nanocl/issues/196

**Comment by cszach** [comment]
> If anyone hasn't started on this, I can take a stab at it. :3

Please go ahead. I haven't been able to work on this lately.

**Comment by 0xle0ne** [comment]
Thank for your return!
I'll assign it to you @tyrone-wu 
Don't be afraid to tell me if you have problem i don't mind doing some peer programming!
