### ISSUE TITLE
Doc: Add docker setup and nanocld docker-host options inside contributing.md

### ISSUE THREAD

**Issue by 0xle0ne** [nxthat/nanocl#201]
I'll need to update the developer documentation with better description in case of docker installed using docker desktop

**Comment by hnidoaht-101** [comment]
hi, just provide more information in case we don't want to handle docker-desktop issue.
Using the command `docker context ls` we can see which docker daemon is being used:
![image](https://user-images.githubusercontent.com/101930794/231121268-c0827715-30b9-4c64-ba84-79ce745d3da2.png)
In my case, I was switch back to `default` context by command `docker context use default`. Then we can follow contributing.md guildeline without any problems.

**Comment by 0xle0ne** [comment]
Nice to know thanks!
