### ISSUE TITLE
Feature: Filter cargoes

### ISSUE THREAD

**Issue by 0xle0ne** [nxthat/nanocl#224]
**Describe the solution you'd like**
Add a new query parameter to filter cargoes on `GET /cargoes` :
- Name: to perform a like on the name
- Limit: to add a limit
- Offset: to add an offset

This will be usefull on the dashboard for example to enable data on scroll.

You can see an example on `GET /namespaces`.

We could also add filter parameters to the cli

**Comment by CreepyPvP** [comment]
Coud i please have this issue?
