### ISSUE TITLE
Feature: Allow network options when creating a namespace

### ISSUE THREAD

**Issue by 0xle0ne** [nxthat/nanocl#286]
**Is your feature request related to a problem? Please describe.**
When creating a namespace, we should take extra optionnal parameters to be abble to setup some network options.

Options to add are relation to options for create a network that can be found [there](https://docs.docker.com/engine/api/v1.42/#tag/Network/operation/NetworkCreate)

This is a DAEMON and CLI change.

A command like this should be considered:

```
nanocl namespace create my-namespace --attachable --gateway 172.25.0.1
```

**Comment by anonkey** [comment]
Think to use Gateway option in c2ncl at this moment
