### ISSUE TITLE
Use TOML rather than YAML

### ISSUE THREAD

**Issue by Dowwie** [nxthat/nanocl#376]
Do you want to build yet another Kubernetes or something better?  YAML is much harder to work with than TOML.  Break from YAML and adopt TOML.

**Comment by 0xle0ne** [comment]
Yeah i saw commentary about this on reddit.
I think the correct move is to handle multiple format: `yaml`, `toml`, `json` and `hcl` seems to be popular choice.
Also this project is not designed to be a exact rewrite of kubernetes, as it will be less creative work..
