### ISSUE TITLE
Feature: Accept optional ssl keys for nanocld

### ISSUE THREAD

**Issue by 0xle0ne** [nxthat/nanocl#389]
**Is your feature request related to a problem? Please describe.**
We need to add optional arguments to use ssl keys for the daemon nanocld.

**Comment by Abhicodes-crypto** [comment]
Hi @leon3s I would like to work on this issue. Can I get more info like which specific files in the codebase I should focus on while working on this task. What are the optional arguments that need to be added.

**Comment by 0xle0ne** [comment]
Hey @Abhicodes-crypto i'm glad you wanna participate!
It's inside `bin/nanocld/src/server.rs` you need to add extrat arguments to handle SSL/TLS.
We will take path of their location from the cli argument inside `bin/nanocld/src/cli.rs`

The values should be:
- `ssl_cert`
- `ssl_key`
- `ssl_ca`

And a command like this should work :
```sh
nanocld --ssl-cert /path/to/cert --ssl-key /path/to/key --ssl-ca /path/to/ca
```

Dont forget to a add tests please !
You can use the ssl key already generated in the `tests` folder or generate new one if needed.

You can find a example [there](https://github.com/ntex-rs/examples/tree/master/openssl) but it should work with a custom `CA` aswell!
