### ISSUE TITLE
Feature: Send event when VM is created/runned/deleted/patched/stopped

### ISSUE THREAD

**Issue by 0xle0ne** [nxthat/nanocl#513]
**Is your feature request related to a problem? Please describe.**
Currently VM don't send event when there are created/runned/deleted/patched/stopped

**Describe the solution you'd like**
The daemon nanocld should emit event when a VM is created/runned/deleted/patched/stopped

**Comment by Joao-Moura** [comment]
Is anyone already working on it? If not, I'll take it.

**Comment by 0xle0ne** [comment]
Hey @Joao-Moura sorry for the delay, no one is working on it you can take it!
