### ISSUE TITLE
Podman instead of Docker

### ISSUE THREAD

**Issue by deadeyesky** [nxthat/nanocl#756]
**Is your feature request related to a problem? Please describe.**
Not quite. All I was thinking is having this work with Podman so that I can migrate my existing architecture to it to make it more secure and lightweight.

**Describe the solution you'd like**
I want there to be a guide on how to use Podman (rather than Docker) as the container ecosystem for Nanocl to be installed on. 

**Describe alternatives you've considered**
Not applicable.

**Additional context**
When I run `sudo nanocl install --docker-host unix:///run/podman/podman.sock` I am able to install on to Podman, but when I try to run a service or start a container it throws a strange error:
```
$ nanocl cargo run my-cargo nginx
[404 Not Found] v0.12.0 is not supported
```
I understand that this may have to do with a version issue, but I thought I should include it so that a tutorial could be made on how to install it correctly.

**Comment by 0xle0ne** [comment]
Hey thanks for the report i will take a look into it!
Would you like to work on the documentation for it ?

**Comment by 0xle0ne** [comment]
I was able to install and use it with ease using the v0.13-nightly on Podman.
The error you got is because you probably have an outdated version of the daemon.
Can you run a
```sh
nanocl version
```

**Comment by 0xle0ne** [comment]
I have updated the doc to mention podman, the last stable version should work properly with it now!

**Comment by deadeyesky** [comment]
> I was able to install and use it with ease using the v0.13-nightly on Podman. The error you got is because you probably have an outdated version of the daemon. Can you run a
> 
> ```shell
> nanocl version
> ```

Yep I got 0.13.0 installed and it seems to install except it gave me a `/run/nanocl/nanocl.sock: Connector has been disconnected` error. Any remedy for this or do you think that I should try to reinstall? Perhaps a subsidiary to this whole project would be an advanced log folder to show the installation process or something, unless it already has that.

**Comment by 0xle0ne** [comment]
The best you can do right now is:
```sh
nanocl uninstall --docker-host unix:///run/podman/podman.sock
# Remove old state
sudo rm -rf /var/lib/nanocl
nanocl install --docker-host unix:///run/podman/podman.sock
```
