### ISSUE TITLE
Feature: Create network inside namespace

### ISSUE THREAD

**Issue by 0xle0ne** [nxthat/nanocl#99]
By default when creating a namespace it will create an associated network and all cargo created will use this network.
End-User may want to create other custom network ?

A command like :
```sh
nanocl namespace global network create my-network
```
or
```sh
nanocl network create --namespace global my-network
```

could be implemented. With associated `list` `remove` and `inspect` methods.

This can improove container network isolation.

**Comment by hnidoaht-101** [comment]
Can I have this plz?

**Comment by 0xle0ne** [comment]
It's more a feature suggestion and open to discussion because it adds complexity and I'm not aware of the difficulty of managing this feature when we have more compatibility for multi node.
I am thinking of using `VXLAN` for internal communication of containers and virtual machines but i never did it before so.

You can investigate if you want for this you need 2 virtual machines in the same network with docker installed. After you play with the docker network command to create `VXLAN` between your machine then start 1 container on each machine and try to ping them to have an overview then you can show me how you did setup that i'll be really interested as we will need to replicate it automatically when we add new nodes in the cluster.

**Comment by 0xle0ne** [comment]
You can probably do tests with 2 docker in docker setup aswell

**Comment by hnidoaht-101** [comment]
> It's more a feature suggestion and open to discussion because it adds complexity and I'm not aware of the difficulty of managing this feature when we have more compatibility for multi node. I am thinking of using `VXLAN` for internal communication of containers and virtual machines but i never did it before so.
> 
> You can investigate if you want for this you need 2 virtual machines in the same network with docker installed. After you play with the docker network command to create `VXLAN` between your machine then start 1 container on each machine and try to ping them to have an overview then you can show me how you did setup that i'll be really interested as we will need to replicate it automatically when we add new nodes in the cluster.

err, I seem to have underestimated this feature, it sounds more complicated than I thought. This is also the first time I heard about  `VXLAN`. I may need to study a bit before practice. Then show you what I have.
